server:
  port: ${PORT:8020}
eureka:
  client:
    serviceUrl:
      defaultZone: http://pds-ppi.herokuapp.com:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: service-bookings
          uri: lb://service-bookings
          predicates:
            - Path=/booking/**
        - id: service-movies
          uri: lb://service-movies
          predicates:
            - Path=/movie/**
        - id: service-showtimes
          uri: lb://service-showtimes
          predicates:
            - Path=/showtime/**
        - id: service-users
          uri: lb://service-users
          predicates:
            - Path=/user/**