server:
  port: 9200
spring:
  application:
    name: service-showtimes
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:showtimesBD;
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  boot:
    admin:
      client:
        url: http://localhost:8030
eureka:
  client:
    serviceUrl:
      defaultZone: http://pds-ppi.herokuapp.com/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"